version: '3.8'

services:
  node:
    build: ./node-app
    container_name: node-app
    restart: unless-stopped
    ports:
      - "3000:3000"  # Optional: for direct access

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8081:80"    # Nginx reverse proxy available on this
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    restart: unless-stopped

